# An instance's env file, and the per-container env files made from it. Sourced by openmrs-docker.

# An instance name is also its Compose project name, which Compose lowercases (and strips of
# anything else), while this tool names volumes and labels from it verbatim.
valid_name() { [[ "$1" =~ ^[a-z0-9][a-z0-9_-]*$ ]]; }
# shellcheck disable=SC2034 # used by openmrs-docker
NAME_RULE="must be lowercase letters, digits, '-' and '_', starting with a letter or digit"

# Prints NAME='value' for an instance's env file. bash sources that file and Docker Compose reads it,
# and single-quoted values are literal to both, so `$`, `"`, backticks and backslashes are safe. A
# single quote or newline can't be written in a form both read the same way, so it's refused.
declare -A ENV_LINES_WRITTEN
env_line() { # <name> <value>
    [[ "$2" != *[$'\'\n\r']* ]] || die "$1 contains a single quote or newline, which an instance's env file can't hold"
    # shellcheck disable=SC2034 # read by cmd_create
    ENV_LINES_WRITTEN[$1]=1
    printf "%s='%s'\n" "$1" "$2"
}

# The lines of an .env.defaults file, with each ${VAR:-default} expanded against the current
# environment, so a value the caller exported (or, for add-service and sync, the instance's env
# already sourced) wins. Other comment lines pass through. A ${VAR:?message} fails the calling
# subshell when VAR isn't set: callers run this inside $(...).
render_env_defaults() { # <file>
    local template=$1 line name resolved
    [ -f "$template" ] || return 0
    while IFS= read -r line || [ -n "$line" ]; do
        # A rule for write_container_env_files, not a line for env.
        [[ "$line" == "# container-env:"* ]] && continue
        if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
            name=${BASH_REMATCH[1]}
            eval "resolved=${BASH_REMATCH[2]}"
            # Later lines can build their default from this one (callers run this in a subshell).
            printf -v "$name" '%s' "$resolved"
            env_line "$name" "$resolved"
        else
            printf '%s\n' "$line"
        fi
    done < "$template"
}

render_service_env_defaults() { render_env_defaults "$SERVICES_DIR/$1.env.defaults"; } # <svc>

# A service whose container takes variables from env declares their name prefixes in its
# .env.defaults ("# container-env: PREFIX_ ..."), and its fragment's env_file is <svc>.env. That file
# is generated here, on every command, with only the matching lines of env, so the container doesn't
# get every secret in it. Without the directive the container gets nothing from env, and a <svc>.env
# left from an earlier directive is removed.
write_container_env_files() { # <instance dir>
    local f svc prefix prefixes=()
    for f in "$1"/*.yaml; do
        [ -e "$f" ] || continue
        svc=$(basename "$f" .yaml)
        read -ra prefixes -d '' < <(sed -n 's/^# container-env://p' "$SERVICES_DIR/$svc.env.defaults" 2>/dev/null) || true
        if [ ${#prefixes[@]} -eq 0 ]; then
            rm -f "$1/$svc.env"
            continue
        fi
        for prefix in "${prefixes[@]}"; do
            [[ "$prefix" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || die "bad container-env prefix '$prefix' in $SERVICES_DIR/$svc.env.defaults"
        done
        (
            umask 077
            echo "# Generated by openmrs-docker from env, on every command. Edit env, not this file."
            grep -E "^($(IFS='|'; echo "${prefixes[*]}"))[A-Za-z0-9_]*=" "$1/env" || true
        ) > "$1/$svc.env"
        chmod 600 "$1/$svc.env"
    done
}

# The variables the instance's fragments require (${VAR?}) that env doesn't set. Their defaults are
# only in the .env.defaults files, so an env written before one was added lacks it.
missing_required_env() {
    local var
    for var in $(grep -ho '\${[A-Za-z_][A-Za-z0-9_]*?' "$INSTANCE_DIR"/*.yaml 2>/dev/null | sed 's/^\${//; s/?$//' | sort -u); do
        grep -q "^$var=" "$ENV_FILE" || echo "$var"
    done
}

# Appends rendered defaults (render_service_env_defaults) to env, skipping names it already has, and
# prints the names it added. --all appends every line, comments included (add-service). --required
# appends only variables the fragments require (sync), so a default deliberately deleted from env,
# such as an OPENMRS_DB_OPT_* server option, isn't put back.
append_missing_env_defaults() { # <rendered defaults> --all|--required
    local line required=""
    [ "$2" = --required ] && required=$(missing_required_env)
    while IFS= read -r line; do
        [ -n "$line" ] || continue
        if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)= ]]; then
            grep -q "^${BASH_REMATCH[1]}=" "$ENV_FILE" && continue
            [ "$2" = --required ] && ! grep -qx "${BASH_REMATCH[1]}" <<< "$required" && continue
            echo "${BASH_REMATCH[1]}"
        elif [ "$2" = --required ]; then
            continue
        fi
        echo "$line" >> "$ENV_FILE"
    done <<< "$1"
}
