name: Build and deploy

on:
  workflow_call:
    inputs:
      image_name:
        description: OpenMRS image name, without tag
        required: true
        type: string
      maven_profiles:
        description: Comma-separated Maven profiles to activate during deploy (e.g. distro-zip)
        required: false
        type: string
        default: ''
    secrets:
      OPENMRS_MAVEN_USERNAME:
        required: true
      OPENMRS_MAVEN_PASSWORD:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'maven'
          server-id: openmrs-repo-modules-pih
          server-username: OPENMRS_MAVEN_USERNAME
          server-password: OPENMRS_MAVEN_PASSWORD

      - name: Maven Deploy
        run: mvn -B -U deploy --file pom.xml${{ inputs.maven_profiles != '' && format(' -P{0}', inputs.maven_profiles) || '' }}
        env:
          OPENMRS_MAVEN_USERNAME: ${{ secrets.OPENMRS_MAVEN_USERNAME }}
          OPENMRS_MAVEN_PASSWORD: ${{ secrets.OPENMRS_MAVEN_PASSWORD }}

      - name: Extract pom version
        run: echo "DOCKER_IMAGE_TAG_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: PIH/openmrs-contrib-distro-tools/.github/actions/build-and-push-docker@main
        with:
          image_name: ${{ inputs.image_name }}
          context: distro/target/distro/web
          version: ${{ env.DOCKER_IMAGE_TAG_VERSION }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
